# docker compose up --detach
services:
  postgres:
    image: postgres
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: walmart
    user: postgres
    ports:
      - "5432:5432"
